### ISSUE TITLE
Licenses for 3rd party open source libraries

### ISSUE THREAD

**Issue by denkeni** [ailabstw/social-distancing-ios#3]
Since the app is built with [some 3rd party open source libraries](https://github.com/ailabstw/social-distancing-ios/blob/3129098ef555096406c0683a234b19c6f9ccdc44/ExposureNotification.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved), there's legal obligation to include respective licenses in the app.

I would suggest using [LicensePlist](https://github.com/mono0926/LicensePlist) to have minimal impact without building another UI, and it could be included within continuous integration.

**Comment by JarvisN0321** [comment]
Thank you for your suggestion.

We will deal with it to include respective licenses in the App.

**Comment by denkeni** [comment]
Resolved with https://github.com/ailabstw/social-distancing-ios/commit/958c9421d08bd46db2da1e6c7cf23515ec2dce02.
